In [91]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from mpl_toolkits.mplot3d import Axes3D


In [92]:
from sklearn.datasets import make_classification
x,y = make_classification(n_classes=2, n_features=2, n_samples=200,n_redundant=0,n_repeated=0,n_informative=2,n_clusters_per_class=1, random_state=1)
x = np.digitize(x, bins=[-0.5,0.5]) 
#bins is breakpoint, like here we have 2 breakpoints -0.5, 0.5 on our data, data<=-0.5, 0.5<data<=0.5, data>0.5

In [93]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.4,random_state=2)

In [94]:
z= x[y==1]

In [95]:
df = pd.DataFrame(x_train)
df[y_train==0][0].value_counts()[2]

51

In [96]:
#one = ((len(y_train[y_train==1])/len(y_train))*(df[y_train==1][0].value_counts()/len(y_train[y_train==1]))*(df[y_train==1][1].value_counts()/len(y_train[y_train==1])))/((len(x_train[x]))*())

In [97]:
x_train = pd.DataFrame(x_train)
x_train

0  1
0    1  2
1    2  1
2    2  2
3    2  2
4    2  0
..  .. ..
115  2  2
116  1  1
117  2  2
118  2  0
119  2  1

[120 rows x 2 columns]

In [98]:
def prob(x_train,x1,x2,y_train,y):
    try:
        return (x_train[y_train==y][0].value_counts()[x1]/len(y_train[y_train==y]))*(x_train[y_train==y][1].value_counts()[x2]/len(y_train[y_train==y]))
    except:
        return 0
def probBot(x_train,x1,x2):
    return ((len(x_train[x_train==x1]))/(len(x_train)))*((len(x_train[x_train==x2]))/len(x_train))
def probY(y):
    return len(y_train[y_train==y])/len(y_train) 
one = np.array(list(map(lambda x:(probY(1)*prob(x_train,x[0],x[1],y_train,1))/probBot(x_train,x[0],x[1]),x_test)))
zero = np.array(list(map(lambda x:(probY(0)*prob(x_train,x[0],x[1],y_train,0))/probBot(x_train,x[0],x[1]),x_test)))
y_pred = np.where(one > zero, 1, 0)

array([0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1,
       0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1,
       0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0])

use normalize true with get on value counts for better code writing

In [99]:
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix, classification_report
accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy: {accuracy * 100:.2f}%")

precision = precision_score(y_test, y_pred)
recall = recall_score(y_test, y_pred)
f1 = f1_score(y_test, y_pred)

print(f"Precision: {precision:.2f}")
print(f"Recall: {recall:.2f}")
print(f"F1 Score: {f1:.2f}")

cm = confusion_matrix(y_test, y_pred)
print(f"Confusion Matrix:\n{cm}")

print(classification_report(y_test, y_pred))

Accuracy: 87.50%
Precision: 0.88
Recall: 0.88
F1 Score: 0.88
Confusion Matrix:
[[34  5]
 [ 5 36]]
              precision    recall  f1-score   support

           0       0.87      0.87      0.87        39
           1       0.88      0.88      0.88        41

    accuracy                           0.88        80
   macro avg       0.87      0.87      0.87        80
weighted avg       0.88      0.88      0.88        80



In [100]:
from sklearn.naive_bayes import BernoulliNB
NaBys = BernoulliNB()
NaBys.fit(np.array(x_train),y_train)
y_pred = NaBys.predict(x_test)
accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy: {accuracy * 100:.2f}%")

precision = precision_score(y_test, y_pred)
recall = recall_score(y_test, y_pred)
f1 = f1_score(y_test, y_pred)

print(f"Precision: {precision:.2f}")
print(f"Recall: {recall:.2f}")
print(f"F1 Score: {f1:.2f}")

cm = confusion_matrix(y_test, y_pred)
print(f"Confusion Matrix:\n{cm}")

print(classification_report(y_test, y_pred))


Accuracy: 78.75%
Precision: 1.00
Recall: 0.59
F1 Score: 0.74
Confusion Matrix:
[[39  0]
 [17 24]]
              precision    recall  f1-score   support

           0       0.70      1.00      0.82        39
           1       1.00      0.59      0.74        41

    accuracy                           0.79        80
   macro avg       0.85      0.79      0.78        80
weighted avg       0.85      0.79      0.78        80

